spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/file:/Users/pc/IdeaProjects/workspace/study/jap-basic-db
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
      url: jdbc:mysql://localhost:3306/your_database_name?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password:
  # MySQL 데이터소스 설정
  jpa:
    hibernate:
      ddl-auto: update      # 엔티티 변경에 따라 자동 테이블 생성/수정
    show-sql: true          # 실행되는 SQL 로그 출력 (개발용)
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: true         # H2 콘솔 활성화
      path: /h2-console     # 콘솔 접속 경로